linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - gofmt
    - revive
    - gci
    - bodyclose
    - dogsled

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/senyabanana/shop-service)
    skip-generated: true

  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: var-naming
        severity: error
      - name: package-comments
        disabled: true

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck