version: '3.8'

services:
  shop-service:
    build: .
    container_name: shop-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      shop-db:
        condition: service_healthy
    networks:
      - shop-network


  shop-db:
    image: postgres:latest
    container_name: shop-db
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - shop-network

volumes:
  postgres_data:

networks:
  shop-network:
    driver: bridge